In [12]:
import pandas as pd
import os

In [3]:
df = pd.read_json("https://www.datos.gov.co/resource/pi36-fdpk.json")
df

,c_digo_regi_n,nombre_regi_n,c_digo_municipio,nombre_municipio,c_digo_habilitaci_n_prestador_salud,raz_n_social_organizaci_n,nombre_sede,n_mero_nit,direcci_n,n_mero_tel_fono,direcci_n_correo_electr_nico,punto
0,7,Oriente,5002,Abejorral,50020436001,E.S.E HOSPITAL SAN JUAN DE DIOS DE ABEJORRAL,HOSPITAL SAN JUAN DE DIOS ABEJORRAL,890980643,CL Circular X Kr Calibio,5748647181,abejhs01@gmail.com,"{'latitude': '5.788458', 'longitude': '-75.426..."
1,6,Occidente,5004,Abriaquí,50040588001,ESE HOSPITAL NUEVO HORIZONTE,ESE HOSPITAL NUEVO HORIZONTE,811032722,CL 9A # 12-59,3104323014,ese@abriaqui-antioquia.gov.co,"{'latitude': '6.632296', 'longitude': '-76.067..."
2,7,Oriente,5021,Alejandría,50210509801,ESE HOSPITAL PBRO LUIS FELIPE ARBELAEZ,ESE HOSPITAL PBRO LUIS FELIPE ARBELAEZ,800029509,KR 19 # 16-70,5748660077,hospitalalejandria@gmail.com,"{'latitude': '6.373932', 'longitude': '-75.140..."
3,8,Suroeste,5030,Amaga,50300437401,E.S.E. HOSPITAL SAN FERNANDO,E.S.E. HOSPITAL SAN FERNANDO,890906346,Cra 51 No 52 81,5748300353,hospital@eseamaga-antioquia.gov.co,"{'latitude': '6.040678', 'longitude': '-75.704..."
4,4,Nordeste,5031,Amalfi,50310209101,E.S.E HOSPITAL EL CARMEN,E.S.E HOSPITAL EL CARMEN,890982101,CL 23 # 23 - 40,5748301803,gerencia@hospitalelcarmen-amalfi-antioquia.gov.co,"{'latitude': '6.910925', 'longitude': '-75.077..."
...,...,...,...,...,...,...,...,...,...,...,...,...
126,4,Nordeste,5885,Yalí,58850211201,E.S.E. HOSPITAL LA MISERICORDIA,E.S.E. HOSPITAL LA MISERICORDIA,890982162,CL 18 # 23-24,5748675655,yalihs01@edatel.net.co,"{'latitude': '6.673346', 'longitude': '-74.842..."
127,5,Norte,5887,Yarumal,58870228401,E.S.E. HOSPITAL SAN JUAN DE DIOS YARUMAL,E.S.E. HOSPITAL SAN JUAN DE DIOS YARUMAL,890981726,KR 23 # 12 - 13,094 8 53 73 73,cuentasmedicas@hospitalyarumal.gov.co,"{'latitude': '6.957323', 'longitude': '-75.414..."
128,4,Nordeste,5890,Yolombó,58900243101,EMPRESA SOCIAL DEL ESTADO HOSPITAL SAN RAFAEL ...,EMPRESA SOCIAL DEL ESTADO HOSPITAL SAN RAFAEL ...,890981536,KR 24 # 13 - 466,5748654859,esehospitalyolombo@gmail.com,"{'latitude': '6.597681', 'longitude': '-75.017..."
129,3,Magdalena Medio,5893,Yondó,58930322701,ESE HOSPITAL HECTOR ABAD GOMEZ,ESE HOSPITAL HECTOR ABAD GOMEZ,800014884,KR 58 # 47B-50,5748325050,esehectorabadgomez@hospitalyondo.gov.co,"{'latitude': '7.005532', 'longitude': '-73.914..."
130,2,Bajo Cauca,5895,Zaragoza,58950588401,ESE HOSPITAL SAN RAFAEL,ESE HOSPITAL SAN RAFAEL,890981117,Brr San Gregorio Diagonal Urbanización Miraflores,5748389044,zarahs01@edatel.net.co,"{'latitude': '7.491112', 'longitude': '-74.868..."

In [5]:
df["X_Lon"] = df["punto"].str["longitude"]
df["Y_Lat"] = df["punto"].str["latitude"]

df["X_Lon"] = pd.to_numeric(df["X_Lon"])
df["Y_Lat"] = pd.to_numeric(df["Y_Lat"])

df

,c_digo_regi_n,nombre_regi_n,c_digo_municipio,nombre_municipio,c_digo_habilitaci_n_prestador_salud,raz_n_social_organizaci_n,nombre_sede,n_mero_nit,direcci_n,n_mero_tel_fono,direcci_n_correo_electr_nico,punto,X_Lon,Y_Lat
0,7,Oriente,5002,Abejorral,50020436001,E.S.E HOSPITAL SAN JUAN DE DIOS DE ABEJORRAL,HOSPITAL SAN JUAN DE DIOS ABEJORRAL,890980643,CL Circular X Kr Calibio,5748647181,abejhs01@gmail.com,"{'latitude': '5.788458', 'longitude': '-75.426...",-75.426663,5.788458
1,6,Occidente,5004,Abriaquí,50040588001,ESE HOSPITAL NUEVO HORIZONTE,ESE HOSPITAL NUEVO HORIZONTE,811032722,CL 9A # 12-59,3104323014,ese@abriaqui-antioquia.gov.co,"{'latitude': '6.632296', 'longitude': '-76.067...",-76.067405,6.632296
2,7,Oriente,5021,Alejandría,50210509801,ESE HOSPITAL PBRO LUIS FELIPE ARBELAEZ,ESE HOSPITAL PBRO LUIS FELIPE ARBELAEZ,800029509,KR 19 # 16-70,5748660077,hospitalalejandria@gmail.com,"{'latitude': '6.373932', 'longitude': '-75.140...",-75.140366,6.373932
3,8,Suroeste,5030,Amaga,50300437401,E.S.E. HOSPITAL SAN FERNANDO,E.S.E. HOSPITAL SAN FERNANDO,890906346,Cra 51 No 52 81,5748300353,hospital@eseamaga-antioquia.gov.co,"{'latitude': '6.040678', 'longitude': '-75.704...",-75.704572,6.040678
4,4,Nordeste,5031,Amalfi,50310209101,E.S.E HOSPITAL EL CARMEN,E.S.E HOSPITAL EL CARMEN,890982101,CL 23 # 23 - 40,5748301803,gerencia@hospitalelcarmen-amalfi-antioquia.gov.co,"{'latitude': '6.910925', 'longitude': '-75.077...",-75.077171,6.910925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,4,Nordeste,5885,Yalí,58850211201,E.S.E. HOSPITAL LA MISERICORDIA,E.S.E. HOSPITAL LA MISERICORDIA,890982162,CL 18 # 23-24,5748675655,yalihs01@edatel.net.co,"{'latitude': '6.673346', 'longitude': '-74.842...",-74.842429,6.673346
127,5,Norte,5887,Yarumal,58870228401,E.S.E. HOSPITAL SAN JUAN DE DIOS YARUMAL,E.S.E. HOSPITAL SAN JUAN DE DIOS YARUMAL,890981726,KR 23 # 12 - 13,094 8 53 73 73,cuentasmedicas@hospitalyarumal.gov.co,"{'latitude': '6.957323', 'longitude': '-75.414...",-75.414931,6.957323
128,4,Nordeste,5890,Yolombó,58900243101,EMPRESA SOCIAL DEL ESTADO HOSPITAL SAN RAFAEL ...,EMPRESA SOCIAL DEL ESTADO HOSPITAL SAN RAFAEL ...,890981536,KR 24 # 13 - 466,5748654859,esehospitalyolombo@gmail.com,"{'latitude': '6.597681', 'longitude': '-75.017...",-75.017438,6.597681
129,3,Magdalena Medio,5893,Yondó,58930322701,ESE HOSPITAL HECTOR ABAD GOMEZ,ESE HOSPITAL HECTOR ABAD GOMEZ,800014884,KR 58 # 47B-50,5748325050,esehectorabadgomez@hospitalyondo.gov.co,"{'latitude': '7.005532', 'longitude': '-73.914...",-73.914267,7.005532
130,2,Bajo Cauca,5895,Zaragoza,58950588401,ESE HOSPITAL SAN RAFAEL,ESE HOSPITAL SAN RAFAEL,890981117,Brr San Gregorio Diagonal Urbanización Miraflores,5748389044,zarahs01@edatel.net.co,"{'latitude': '7.491112', 'longitude': '-74.868...",-74.868221,7.491112

In [13]:
csv_temporal = os.path.join(arcpy.env.scratchFolder, "datos.csv")
df.to_csv(csv_temporal)

In [14]:
arcpy.management.XYTableToPoint(
    in_table = csv_temporal, 
    out_feature_class = "puntos", 
    x_field = "X_Lon", 
    y_field = "Y_Lat"
)